Q1. Import the numpy package under the name np

In [ ]:
import pandas as pd
import numpy as np

Q2. Print the numpy version and the configuration

In [ ]:
print(np.__version__)

1.21.6


In [ ]:
print(np.show_config())

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

Q3. Create a null vector of size 10

In [ ]:
null_vector=np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Q4.How to find the memory size of any array

In [ ]:
arr=np.arange(1,25,2).reshape(3,4)

#Checking Size of the arr
print("Size of the array: ",arr.size)
 
#Memory size of one arr element in bytes
print("Memory size of one array element in bytes: ",arr.itemsize)
 
# memory size of numpy array in bytes
print("Memory size of numpy array in bytes:",arr.size * arr.itemsize)

Size of the array:  12
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 96


Q5. How to get the documentation of the numpy add function from the command line?

In [ ]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

Q6. Create a null vector of size 10 but the fifth value which is 1

In [ ]:
arr1=np.zeros(10)
arr1[4]=1
arr1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Q7. Create a vector with values ranging from 10 to 49

In [ ]:
arr3=np.arange(10,50)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Q8. Reverse a vector (first element becomes last)

In [ ]:
arr3[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

Q9. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
arr4=np.arange(0,9).reshape(3,3)
arr4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Q10.Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
arr5=np.array([1,2,0,0,4,0])
ind=arr5.nonzero()
ind

(array([0, 1, 4]),)

Q11. Create a 3x3 identity matrix

In [ ]:
id_mat=np.identity(3,int)
id_mat

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Q12. Create a 3x3x3 array with random values

In [ ]:
arr6=np.arange(1,28).reshape(3,3,3)
arr6

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

Q13. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
arr6=np.arange(1,201,2).reshape(10,10)
print("Minimum value in given array is:",arr6.min())

print("Maximum value in given array is:",arr6.max())

Minimum value in given array is: 1
Maximum value in given array is: 199


Q14. Create a random vector of size 30 and find the mean value

In [ ]:
arr6=np.arange(30)
arr6.mean()

14.5

Q15.Create a 2d array with 1 on the border and 0 inside

In [ ]:
arr7=np.ones(25,int).reshape(5,5)
arr7[1:-1,1:-1]=0

arr7

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

Q16.How to add a border (filled with 0's) around an existing array?

In [ ]:
arr8=np.ones(9,int).reshape(3,3)
print(arr8)

print("0 on the border of arr8")
arr8 = np.pad(arr8, pad_width=1, mode='constant', constant_values=0)

arr8

[[1 1 1]
 [1 1 1]
 [1 1 1]]
0 on the border of arr8


array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

Q17.Create a 5x5 matrix with values 1,2,3,4 at diagonal

In [ ]:
arr9=np.diag([1,2,3,4])
arr9

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
arr9.diagonal()

array([1, 2, 3, 4])

In [ ]:
print(np.fliplr(arr9).diagonal())  # Horizontal flip

print(np.flipud(arr9).diagonal())  # Vertical flip

[0 0 0 0]
[0 0 0 0]


In [ ]:
np.where(arr9 < arr9.diagonal(), arr9, -1)  # -1 is broadcast

array([[-1,  0,  0,  0],
       [ 0, -1,  0,  0],
       [ 0,  0, -1,  0],
       [ 0,  0,  0, -1]])

Q18.Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
ar = np.ones((3,3))
print("Checkerboard pattern:")
ar = np.zeros((8,8),dtype=int)
ar[1::2,::2] = 1
ar[::2,1::2] = 1
print(ar)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Q19.Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
arr19=np.arange(336).reshape(6,7,8)
print(arr19)
print("Index of 100 is: ")
np.where(arr19 == 100)

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

(array([1]), array([5]), array([4]))

Q20.Create a checkerboard 8x8 matrix using the tile function

In [ ]:
#Checkerboard matrix using the tile function
new=np.tile([[0,1],[1,0]],(4,4))
print(new)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
